# frozen_string_literal: true

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = "--pattern src/fab_tcg_data_ruby/spec/**{,/*/**}/*_spec.rb"
end

task default: :spec